events { worker_connections 1024; }

http {
    upstream backend {
        server app-1:8080;
        server app-2:8080;
    }

    server {
        listen 80;

        location / {
                    root /usr/share/nginx/html;
                    index index.html;
                }

        location /stocks { proxy_pass http://backend/stocks; }
                location /wallets { proxy_pass http://backend/wallets; }
                location /log { proxy_pass http://backend/log; }
                location /chaos { proxy_pass http://backend/chaos; }
    }
}